module.exports = {
    PARSE_EXCEL: "PARSE_EXCEL",
    GET_ALL_CERTIFICATES: "GET_ALL_CERTIFICATES",
    GENERATE_CERTIFICATES: "GENERATE_CERTIFICATES",
    CHANGE_CERTIFICATE_STATES: "CHANGE_CERTIFICATE_STATES"
}